#+title: Guia Introdutório de /DOT/
#+author: Gabriel Proença Alves

* Prólogo

** O que é /DOT/?

É uma linguagem de marcação utilizada para desenhar diagramas, grafos
descritivos e redes de informações (estruturadas ou não).

Por ser uma linguagem simples, podemos gerar, por meio dela,
infográficos de forma prática e personalizável.

Ela também pode ser usada em diversas situações e áreas do
conhecimento, como no planejamento de redes, bioinformática,
engenharia de software, desenvolvimento web com banco de dados e
machine learning.

Além disso, ela permite facilmente o seu versionamento, uma vez que os
códigos /DOT/ são armazenados em arquivos de texto simples.

Um arquivo de instruções /DOT/ é interpretado por um conjunto de
programas chamado /Graphviz/. Eles são capazes de manipular
rapidamente grafos complexos e gerar saídas em diversos formatos,
consumindo pouquíssimos recursos do /hardware/.

* Os primeiros passos

** Elementos

Mas antes de usufruirmos de todas estas vantagens, precisamos entender
alguns dos conceitos básicos desta linguagem. De modo geral, os
elementos fundamentais presentes em todo arquivo de instruções /DOT/
são as arestas, nós e grafos, ou =edges=, =nodes= e =graphs= na
terminologia oficial da linguagem.

As arestas são traços que interligam pontos; estes pontos possuem
nomes e posições únicas, e são os chamados nós. Enquanto um grafo é
toda a área onde os outros dois objetos anteriores são inseridos. Veja
a seguir um exemplo prático:

# Inserir um simples exemplo código e seu resultado visual com
# legendas explicativas.
